version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: blaseball
    ports: 
      - '5432:5432'
    volumes:
      - bet-db:/var/lib/postgresql/data

  bettingapp:
    build:
      context: .
    environment:
      DB_SCHEMA: postgres
      DB_USER: admin
      DB_PASSWORD: blaseball
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - '3000:3000'
        
volumes:
  bet-db: